// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGTV-5TIxLPCHqBYJkUjEVkVvgBQtF2kE',
    appId: '1:542054048777:android:b3a5fdb1aec9d220fbc4d8',
    messagingSenderId: '542054048777',
    projectId: 'may15proj',
    storageBucket: 'may15proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe6Maj1fr1t0FuM90oNukgPXBUnYgOAK8',
    appId: '1:542054048777:ios:ee778cfe2e8a2359fbc4d8',
    messagingSenderId: '542054048777',
    projectId: 'may15proj',
    storageBucket: 'may15proj.appspot.com',
    androidClientId: '542054048777-99t297d2rsjfqfs36fqkkpk1bu6h98d1.apps.googleusercontent.com',
    iosClientId: '542054048777-ff9rpmq4cp6d71kg9aolqof0ju5rj5vh.apps.googleusercontent.com',
    iosBundleId: 'com.example.may15',
  );
}
